import * as ts from 'typescript';

export const COMMON_IDENTIFIERS = {
  arg: ts.factory.createIdentifier('arg'),
  add: ts.factory.createIdentifier('add'),
  get: ts.factory.createIdentifier('get'),
  getAll: ts.factory.createIdentifier('getAll'),
  put: ts.factory.createIdentifier('put'),
  init: ts.factory.createIdentifier('init'),
  index: ts.factory.createIdentifier('index'),
  store: ts.factory.createIdentifier('store'),
  db: ts.factory.createIdentifier('db'),
  mode: ts.factory.createIdentifier('mode'),
  count: ts.factory.createIdentifier('count'),
  globalThis: ts.factory.createIdentifier('globalThis'),
  undefined: ts.factory.createIdentifier('undefined'),
  storeNames: ts.factory.createIdentifier('storeNames'),
  // methodName: ts.factory.createIdentifier('methodName'),
  options: ts.factory.createIdentifier('options'),
  onerror: ts.factory.createIdentifier('onerror'),
  onsuccess: ts.factory.createIdentifier('onsuccess'),
  resolve: ts.factory.createIdentifier('resolve'),
  reject: ts.factory.createIdentifier('reject'),
  result: ts.factory.createIdentifier('result'),
  transaction: ts.factory.createIdentifier('transaction'),
  withJoins: ts.factory.createIdentifier('withJoins'),
  Array: ts.factory.createIdentifier('Array'),
  Error: ts.factory.createIdentifier('Error'),
  IDBDatabase: ts.factory.createIdentifier('IDBDatabase'),
  IDBRequest: ts.factory.createIdentifier('IDBRequest'),
  IDBTransaction: ts.factory.createIdentifier('IDBTransaction'),
  IDBTransactionMode: ts.factory.createIdentifier('IDBTransactionMode'),
  DBOpenRequest: ts.factory.createIdentifier('DBOpenRequest'),
  DBAddRequest: ts.factory.createIdentifier('DBAddRequest'),
  DBGetRequest: ts.factory.createIdentifier('DBGetRequest'),
  DBPutRequest: ts.factory.createIdentifier('DBPutRequest'),
  Map: ts.factory.createIdentifier('Map'),
  Object: ts.factory.createIdentifier('Object'),
  Promise: ts.factory.createIdentifier('Promise'),
  Reflect: ts.factory.createIdentifier('Reflect'),
  Set: ts.factory.createIdentifier('Set'),
  ReadonlyArray: ts.factory.createIdentifier('ReadonlyArray'),
};
